services:
  - type: web
    name: mcp-server
    env: python
    buildCommand: |
      # Instalar dependências Python
      pip install -r requirements.txt
      # Instalar NLTK e baixar recursos necessários
      python -m pip install nltk
      python -c "import nltk; nltk.download('stopwords', quiet=True); nltk.download('punkt', quiet=True)"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CACHE_ENABLED
        value: "True"
      - key: CACHE_MAX_SIZE
        value: "50"
      - key: LOG_LEVEL
        value: "INFO"
      - key: MAX_RESOURCES_DEFAULT
        value: "15"
      - key: MIN_NODES_DEFAULT
        value: "15"
      - key: DEFAULT_LANGUAGE
        value: "pt"
      - key: YOUTUBE_MAX_RESULTS
        value: "5"
