"""
Predefined category data for the MCP Server.
"""

from typing import Dict, List, Any

# Category definitions
CATEGORIES: Dict[str, Dict[str, Any]] = {
    "technology": {
        "keywords": ["programação", "software", "hardware", "desenvolvimento", "código", "app", "aplicativo", 
                    "tecnologia", "computador", "internet", "web", "digital", "programador", "developer",
                    "programming", "development", "computer", "code", "coding", "algorithm", "data", "system",
                    "network", "database", "cloud", "api", "framework", "library", "interface", "mobile"],
        "subtopics": [
            "Fundamentos de {topic}",
            "Ferramentas para {topic}",
            "Frameworks de {topic}",
            "Boas práticas em {topic}",
            "Arquitetura de {topic}",
            "Testes em {topic}",
            "Segurança em {topic}",
            "Otimização de {topic}",
            "Tendências em {topic}",
            "Implementação de {topic}",
            "Configuração de {topic}",
            "Depuração de {topic}",
            "Introdução a {topic}",
            "Avançando em {topic}",
            "Desenvolvimento com {topic}",
            "Integração de {topic}",
            "Escalabilidade em {topic}",
            "Manutenção de {topic}"
        ],
        "resource_queries": [
            "{topic} tutorial",
            "{topic} documentation",
            "{topic} best practices",
            "{topic} examples",
            "{topic} guide",
            "{topic} for beginners",
            "{topic} advanced techniques",
            "{topic} implementation",
            "{topic} architecture",
            "{topic} security"
        ]
    },
    "finance": {
        "keywords": ["finanças", "dinheiro", "investimento", "economia", "mercado", "bolsa", "ações", 
                    "poupança", "orçamento", "financeiro", "banco", "crédito", "financeira", "monetário",
                    "finance", "money", "investment", "economy", "market", "stock", "shares", "savings",
                    "budget", "financial", "bank", "credit", "monetary", "trading", "fund", "asset"],
        "subtopics": [
            "Princípios básicos de {topic}",
            "Planejamento de {topic}",
            "Estratégias de {topic}",
            "Gestão de riscos em {topic}",
            "Análise de {topic}",
            "Tendências em {topic}",
            "Regulamentação de {topic}",
            "Ferramentas para {topic}",
            "Estudos de caso em {topic}",
            "Orçamento para {topic}",
            "Investimentos em {topic}",
            "Tributação em {topic}",
            "Fundamentos de {topic}",
            "Mercados de {topic}",
            "Indicadores de {topic}",
            "Diversificação em {topic}",
            "Planejamento de {topic} a longo prazo",
            "Gestão de {topic} pessoal"
        ],
        "resource_queries": [
            "{topic} guia",
            "{topic} tutorial",
            "{topic} explicado",
            "{topic} para iniciantes",
            "{topic} avançado",
            "{topic} estratégias",
            "{topic} análise",
            "{topic} mercado",
            "{topic} tendências",
            "{topic} regulamentação"
        ]
    },
    "health": {
        "keywords": ["saúde", "bem-estar", "medicina", "fitness", "nutrição", "exercício", "dieta", 
                    "médico", "terapia", "mental", "corpo", "mente", "doença", "prevenção",
                    "health", "wellness", "medicine", "fitness", "nutrition", "exercise", "diet",
                    "medical", "therapy", "mental", "body", "mind", "disease", "prevention",
                    "healthcare", "treatment", "diagnosis", "symptom", "condition", "patient"],
        "subtopics": [
            "Fundamentos de {topic}",
            "Benefícios de {topic}",
            "Práticas recomendadas para {topic}",
            "Riscos associados a {topic}",
            "Pesquisas sobre {topic}",
            "Aplicações de {topic}",
            "Técnicas de {topic}",
            "Equipamentos para {topic}",
            "Profissionais de {topic}",
            "Prevenção através de {topic}",
            "Tratamentos com {topic}",
            "Histórico de {topic}",
            "Avanços em {topic}",
            "Diagnóstico em {topic}",
            "Cuidados com {topic}",
            "Reabilitação em {topic}",
            "Nutrição e {topic}",
            "Exercícios para {topic}"
        ],
        "resource_queries": [
            "{topic} guia completo",
            "{topic} benefícios",
            "{topic} como funciona",
            "{topic} dicas",
            "{topic} profissional",
            "{topic} tratamento",
            "{topic} prevenção",
            "{topic} pesquisas recentes",
            "{topic} técnicas",
            "{topic} cuidados"
        ]
    },
    "education": {
        "keywords": ["educação", "aprendizagem", "ensino", "escola", "faculdade", "universidade", 
                    "curso", "aula", "professor", "aluno", "estudante", "pedagogia", "didática",
                    "education", "learning", "teaching", "school", "college", "university",
                    "course", "class", "teacher", "student", "pedagogy", "didactics",
                    "curriculum", "instruction", "academic", "study", "knowledge", "training"],
        "subtopics": [
            "Metodologias de {topic}",
            "Recursos para {topic}",
            "Avaliação em {topic}",
            "Tecnologias para {topic}",
            "Desafios em {topic}",
            "Tendências em {topic}",
            "Práticas de {topic}",
            "Teorias de {topic}",
            "Aplicações de {topic}",
            "Desenvolvimento de {topic}",
            "Estratégias de {topic}",
            "Inovação em {topic}",
            "Fundamentos de {topic}",
            "Currículo de {topic}",
            "Formação em {topic}",
            "Pesquisa em {topic}",
            "Inclusão em {topic}",
            "Avaliação de {topic}"
        ],
        "resource_queries": [
            "{topic} metodologia",
            "{topic} recursos",
            "{topic} aplicações",
            "{topic} guia para professores",
            "{topic} para estudantes",
            "{topic} práticas",
            "{topic} teorias",
            "{topic} tecnologias",
            "{topic} avaliação",
            "{topic} desenvolvimento"
        ]
    },
    "arts": {
        "keywords": ["arte", "música", "pintura", "literatura", "cinema", "teatro", "dança", 
                    "escultura", "fotografia", "design", "criativo", "cultural", "artístico",
                    "art", "music", "painting", "literature", "cinema", "theater", "dance",
                    "sculpture", "photography", "design", "creative", "cultural", "artistic",
                    "visual", "performance", "exhibition", "gallery", "composition", "craft"],
        "subtopics": [
            "História de {topic}",
            "Técnicas de {topic}",
            "Estilos de {topic}",
            "Materiais para {topic}",
            "Artistas de {topic}",
            "Movimentos em {topic}",
            "Análise de {topic}",
            "Criação de {topic}",
            "Apreciação de {topic}",
            "Exposições de {topic}",
            "Tendências em {topic}",
            "Ensino de {topic}",
            "Fundamentos de {topic}",
            "Composição em {topic}",
            "Crítica de {topic}",
            "Conservação de {topic}",
            "Interpretação de {topic}",
            "Evolução de {topic}"
        ],
        "resource_queries": [
            "{topic} técnicas",
            "{topic} história",
            "{topic} como fazer",
            "{topic} exemplos",
            "{topic} para iniciantes",
            "{topic} artistas",
            "{topic} movimentos",
            "{topic} análise",
            "{topic} materiais",
            "{topic} exposições"
        ]
    },
    "science": {
        "keywords": ["ciência", "física", "química", "biologia", "matemática", "astronomia", 
                    "geologia", "pesquisa", "laboratório", "experimento", "científico", "teoria",
                    "science", "physics", "chemistry", "biology", "mathematics", "astronomy",
                    "geology", "research", "laboratory", "experiment", "scientific", "theory",
                    "hypothesis", "data", "analysis", "observation", "discovery", "methodology"],
        "subtopics": [
            "Princípios de {topic}",
            "Experimentos em {topic}",
            "Teorias de {topic}",
            "Aplicações de {topic}",
            "História de {topic}",
            "Avanços em {topic}",
            "Metodologia de {topic}",
            "Equipamentos para {topic}",
            "Pesquisadores de {topic}",
            "Descobertas em {topic}",
            "Futuro de {topic}",
            "Impacto de {topic}",
            "Fundamentos de {topic}",
            "Análise de dados em {topic}",
            "Observações em {topic}",
            "Hipóteses sobre {topic}",
            "Modelos de {topic}",
            "Simulações de {topic}"
        ],
        "resource_queries": [
            "{topic} explicado",
            "{topic} pesquisa",
            "{topic} teoria",
            "{topic} aplicações",
            "{topic} experimentos",
            "{topic} descobertas",
            "{topic} metodologia",
            "{topic} avanços recentes",
            "{topic} fundamentos",
            "{topic} história"
        ]
    },
    "business": {
        "keywords": ["negócios", "empreendedorismo", "empresa", "startup", "gestão", "marketing", 
                    "vendas", "administração", "liderança", "estratégia", "comercial", "mercado",
                    "business", "entrepreneurship", "company", "startup", "management", "marketing",
                    "sales", "administration", "leadership", "strategy", "commercial", "market",
                    "enterprise", "corporate", "organization", "commerce", "industry", "trade"],
        "subtopics": [
            "Fundamentos de {topic}",
            "Estratégias de {topic}",
            "Gestão de {topic}",
            "Análise de {topic}",
            "Tendências em {topic}",
            "Ferramentas para {topic}",
            "Casos de sucesso em {topic}",
            "Desafios em {topic}",
            "Inovação em {topic}",
            "Planejamento de {topic}",
            "Métricas para {topic}",
            "Liderança em {topic}",
            "Marketing de {topic}",
            "Finanças em {topic}",
            "Operações de {topic}",
            "Recursos humanos em {topic}",
            "Expansão de {topic}",
            "Modelos de {topic}"
        ],
        "resource_queries": [
            "{topic} estratégias",
            "{topic} guia",
            "{topic} cases",
            "{topic} ferramentas",
            "{topic} tendências",
            "{topic} gestão",
            "{topic} planejamento",
            "{topic} métricas",
            "{topic} inovação",
            "{topic} liderança"
        ]
    },
    "lifestyle": {
        "keywords": ["estilo de vida", "hobby", "lazer", "viagem", "culinária", "gastronomia", 
                    "decoração", "moda", "jardinagem", "pets", "animais", "casa", "família",
                    "lifestyle", "hobby", "leisure", "travel", "cooking", "gastronomy",
                    "decoration", "fashion", "gardening", "pets", "animals", "home", "family",
                    "wellness", "self-care", "entertainment", "recreation", "crafts", "diy"],
        "subtopics": [
            "Introdução a {topic}",
            "Técnicas de {topic}",
            "Equipamentos para {topic}",
            "Tendências em {topic}",
            "Dicas para {topic}",
            "Benefícios de {topic}",
            "Comunidades de {topic}",
            "Eventos de {topic}",
            "História de {topic}",
            "Projetos de {topic}",
            "Inspirações para {topic}",
            "Personalização de {topic}",
            "Fundamentos de {topic}",
            "Guia para iniciantes em {topic}",
            "Avançando em {topic}",
            "Melhores práticas em {topic}",
            "Recursos para {topic}",
            "Experiências com {topic}"
        ],
        "resource_queries": [
            "{topic} dicas",
            "{topic} como começar",
            "{topic} ideias",
            "{topic} tutoriais",
            "{topic} inspiração",
            "{topic} guia",
            "{topic} técnicas",
            "{topic} equipamentos",
            "{topic} tendências",
            "{topic} comunidades"
        ]
    },
    "general": {
        "keywords": [],  # Default category, no specific keywords
        "subtopics": [
            "Introdução a {topic}",
            "Fundamentos de {topic}",
            "Aplicações de {topic}",
            "História de {topic}",
            "Técnicas de {topic}",
            "Ferramentas para {topic}",
            "Tendências em {topic}",
            "Práticas recomendadas para {topic}",
            "Recursos para {topic}",
            "Comunidade de {topic}",
            "Futuro de {topic}",
            "Impacto de {topic}",
            "Desenvolvimento de {topic}",
            "Análise de {topic}",
            "Estratégias de {topic}",
            "Desafios em {topic}",
            "Benefícios de {topic}",
            "Exemplos de {topic}"
        ],
        "resource_queries": [
            "{topic} guia",
            "{topic} tutorial",
            "{topic} explicado",
            "{topic} exemplos",
            "{topic} recursos",
            "{topic} introdução",
            "{topic} fundamentos",
            "{topic} aplicações",
            "{topic} história",
            "{topic} tendências"
        ]
    }
}
